config/routes.rb
Jumpcraft::Application.routes.draw do
  root to: "home#index"
  devise_for :users, token_authentication_key: 'auth_token', controllers: {sessions: 'sessions'}

  get '/home/play'        => 'home#play', as: 'play'
  get '/users/ladder'     => 'users#ladder', as: 'users_ladder'
  get '/users/:id'        => 'users#show', as: 'user'

  get '/maps/ladder'      => 'maps#ladder', as: 'maps_ladder'
  get '/maps/my_maps'     => 'maps#my_maps', as: 'maps_my_maps'
  get '/maps/suggestions' => 'maps#suggestions', as: 'maps_suggestions'
  get '/maps/near_score'  => 'maps#near_score', as: 'maps_near_score'
  get '/maps/:id'         => 'maps#show', as: 'map'
  post '/maps'            => 'maps#create'

  get '/games/my_games'   => 'games#my_games'
  post '/games/start'     => 'games#start'
  post '/games/finish'    => 'games#finish'
  post '/games/update_tutorial' => 'games#update_tutorial'
end

app/views/layouts/_navigation.html.haml
%ul.nav.pull-left
  %li{class: ('active' if current_page?(root_path))}= link_to 'Home', root_path
  %li{class: ('active' if current_page?(play_path))}= link_to 'Build & Play', play_path
  %li{class: ('active' if current_page?(users_ladder_path))}= link_to 'Top Players', users_ladder_path
  %li{class: ('active' if current_page?(maps_ladder_path))}= link_to 'Top Challenges', maps_ladder_path
  - if user_signed_in?
    %li{class: ('active' if current_page?(maps_my_maps_path))}= link_to 'My Creations', maps_my_maps_path
    %li{class: ('active' if current_page?(games_my_games_path))}= link_to 'My Play History', games_my_games_path


%ul.nav.pull-right
  - if user_signed_in?
    %li.dropdown
      %a.dropdown-toggle(data-toggle="dropdown" href="#" role="button")
        %i.icon-user
        = current_user.name
        %b.caret
      %ul.dropdown-menu(role="menu" aria-labelledby="dLabel")
        %li
          %a{ href: url_for(current_user) }
            %i.icon-user
            My profile
        %li
          %a{ href: edit_user_registration_path }
            %i.icon-edit
            Edit account
        %li
          %a{ href: destroy_user_session_path, data: {method: 'delete'}, rel: 'nofollow' }
            %i.icon-off
            Logout

  - else
    %li
      = link_to 'Sign in', new_user_session_path
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")

    - if content_for?(:og_meta)
      = yield(:og_meta)
    - else
      %meta(property="og:title"       content="Jumpcraft")
      %meta(property="og:description" content="Jumpcraft is a game where you can play, build, and share 2D platformer levels.")
      %meta(property="og:image"       content="http://jumpcraft.herokuapp.com/jumpcraft-cover-city.png")

    %title= content_for?(:title) ? yield(:title) : "Jumpcraft"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="/favicon.ico?v=1" rel="shortcut icon")

    / Bootstrap current_user data in JS
    - if user_signed_in?
      :javascript
        window.current_user = #{current_user.attrs_for_flash.to_json};

    / Other JS bootstrap data from views
    = yield :bootstrap_javascripts

  %body
    #wrap
      .navbar.navbar-fixed-top
        .navbar-inner
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          .nav-collapse
            = render 'layouts/navigation'

      #top-padding.container
      = yield
      #push

    #footer
      .container
        %p.muted.credit
          Jumpcraft was designed and implemented by Mario Izquierdo and Alex Cho Snyder.
          Find the source code in
          %a(href="https://github.com/marioizquierdo/jumpcraft") github.

    / Javascripts
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

    = yield :javascripts

    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-54138184-1', 'auto');
      ga('send', 'pageview');

      if (window.current_user) {
        ga('set', '&uid', window.current_user._id);
      }